task.15.2.a MySQL database integration test
Niebieska-2020/aga_furman-kodilla_tester pull request #75
Opened 2020-06-27 15:34 UTC by Niebieska-2020

2020-06-27 23:38 UTC, mps4dev requested changes
hmmm

2020-06-27 23:38 UTC, mps4dev commented on kodilla-code-coverage/src/test/java/com/kodilla/jdbc/DbManagerTestSuite.java
> +        String countQuery = "SELECT COUNT(*) AS USERS FROM kodilla_tester.users WHERE ID IN (SELECT USER_ID FROM POSTS GROUP BY USER_ID HAVING COUNT(*) >= 2)";
co tu sie dzieje? W tabeli POSTS chyba jest zero wpisow jeszcze). Nie rozumiem podzapytania.

2020-06-28 07:01 UTC, Niebieska-2020 commented on kodilla-code-coverage/src/test/java/com/kodilla/jdbc/DbManagerTestSuite.java
> +        String countQuery = "SELECT COUNT(*) AS USERS FROM kodilla_tester.users WHERE ID IN (SELECT USER_ID FROM POSTS GROUP BY USER_ID HAVING COUNT(*) >= 2)";
Są wpisy. W poprzednim module 8 robiliśmy taką tabelę i tutaj się do niej odwołuję. Tabela Users w kodilla_testerr.users ma połączenie po user_is z tabelą posts i dlatego chcę wybrać tylko tych usersów co mają powyżej 2ch postów i ich policzyć

2020-06-30 23:26 UTC, mps4dev approved these changes
👍

2020-07-01 08:42 UTC, merged